### ISSUE TITLE
Example!!

### ISSUE THREAD

**Issue by Valentjno** [detly/gammatone#14]
I can have an example of Gamma tone gram generation written in Python?
![image](https://user-images.githubusercontent.com/38430033/95188236-6d18d980-07cc-11eb-80b4-50b917066b91.png)

**Comment by detly** [comment]
It depends on what exactly you need. In the readme file it shows how you can do it from the command line with:

    python -m gammatone FurElise.wav -d 10

All this does is call [`render_audio_from_file`](https://github.com/detly/gammatone/blob/master/gammatone/plot.py#L105). Does that answer your question?

**Comment by Valentjno** [comment]
Thank you! But in this case in the method "render_audio_from_file" the "function" parameter is just: 
-> function = gammatone.gtgram.gtgram ?
Is there any parameter that escapes me?

**Comment by detly** [comment]
> -> function = gammatone.gtgram.gtgram ?

This parameter is the function used to create the gammatone spectrogram, it can be either:

- `gammatone.gtgram.gtgram` - the slower but more accurate method that uses a full gammatone filterbank
- `gammatone.fftweight.fft_gtgram` - the faster method (but less precise) that uses weights applied to an FFT

The other parameters are the `path` to the `.wav` file and the time in seconds from the start you want to render until.
