### ISSUE TITLE
Submit to pypi

### ISSUE THREAD

**Issue by quancs** [detly/gammatone#16]
Hello, can you submit this package to Pypi, seems the name is still available.

**Comment by detly** [comment]
Sorry, I no longer have the time to maintain the code itself, let alone publish a package. I have no problem with someone else doing so, however.

**Comment by Borda** [comment]
> Sorry, I no longer have the time to maintain the code itself, let alone publish a package. I have no problem with someone else doing so, however.

could you consider adding me to help with some work? :rabbit:

**Comment by detly** [comment]
> could you consider adding me to help with some work? 🐰

No, I will be archiving most of my projects soon, so there's little point. You (or anyone else) are, of course, free to fork it. (I solemnly promise that I will not suddenly dispute ownership of the package name if it does appear on PyPi or elsewhere.)

**Comment by Borda** [comment]
ok, in such a case, would you consider donating/porting your coder to be part of TorchMetrics? :pray:

**Comment by christianbrodbeck** [comment]
I'd also be interested in seeing this as a community maintained package on `PYPI` , although I'd suggest keeping it a separate module so as to keep minimal dependencies?

**Comment by Borda** [comment]
FYI, I am doing so cleaning in https://github.com/Lightning-Sandbox/gammatone
and pushing the release of the actual state https://pypi.org/project/Gammatone/ and will add fixed versions later...
