### ISSUE TITLE
Reconstruction

### ISSUE THREAD

**Issue by jorgemadridportillo** [detly/gammatone#8]
Hi,

Is there a way to reconstruct the time domain signal from the gammatone-gram representation?

Thanks!

**Comment by pramodhrachuri** [comment]
Hi,
Any updates on this?
Thanks

**Comment by whmrtm** [comment]
Same question here, any updates?

**Comment by bingo-todd** [comment]
Directly add all frequency channels up after compensating phase delay ?

**Comment by marinelliluca** [comment]
It is impossible to reconstruct guys, you can't invert a 'compressed' representation into an STFT.
